# Environment
environment=QA

# Base URL
base.url=https://reqres.in
api.key=free_user_3G7dMjEwe3O5mIOXkZ4QCQWGVs1

# Authentication
username=
password=
token=

# Timeout
connection.timeout=30
read.timeout=30

# Logging
request.logging=true
response.logging=true